on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
      
    - name: 🔨 Build Project
      run: |
        npm ci
        npm run build
    
    - name: List output files
      run: ls -R dist
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.n8s.pw
        username: deploy@n8s.pw
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
