on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
    
    - name: List output files
      run: ls -R dist
      
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ftp.n8s.pw
        username: deploy@n8s.pw
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
